//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACT
    {
        public Nullable<short> FACTID { get; set; }
        public string FACTNAME { get; set; }
        public System.DateTime FACTDATE { get; set; }
    }
}
