//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SledDogEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mushing : Team
    {
        public string Leader1 { get; set; }
        public string Leader2 { get; set; }
    }
}
