//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SledDogEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skijoring : Team
    {
        public string Dog1 { get; set; }
        public string Dog2 { get; set; }
        public string Dog3 { get; set; }
        public int NumberOfLeaders { get; set; }
    }
}
