//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SledDogEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int DougCount { get; set; }
        public int RaceRaceId { get; set; }
    
        public virtual Race Race { get; set; }
    }
}
